name: Generate release APK and AAB

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
        
      - name: Generate apikey.properties
        run: |
          cat <<EOF > apikey.properties
          DATADOG_LOGGER_NAME:"${{ vars.DATADOG_LOGGER_NAME }}"
          DATADOG_CLIENT_TOKEN:"${{ secrets.DATADOG_CLIENT_TOKEN }}"
          ZENDESK_URL:"${{ vars.ZENDESK_URL }}"
          ZENDESK_APP_ID:"${{ secrets.ZENDESK_APP_ID }}"
          ZENDESK_OAUTH_ID:"${{ secrets.ZENDESK_OAUTH_ID }}"
          ZENDESK_CHAT_ACCOUNT_KEY:"${{ secrets.ZENDESK_CHAT_ACCOUNT_KEY }}"
          EOF

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEYSTORE_STORE_PASSWORD }}
          keyPassword:${{ secrets.KEYSTORE_KEY_PASSWORD }}
          keyAlias:${{ secrets.KEYSTORE_KEY_ALIAS }}
          storeFile:${{ vars.KEYSTORE_STORE_FILE_PATH }}
          EOF

      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > keystore.jks
          
      - name: Generate file name env var
        run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          AppName-release-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/release/app-release.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"

      - name: Upload release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk

      - name: Build release AAB
        run: bash ./gradlew bundleRelease --stacktrace

      - name: Rename AAB 
        run:
          mv "./app/build/outputs/bundle/release/app-release.aab" "./app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab"
        
      - name: Upload debug AAB
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab
          